import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';
const wordsReceipt=execFileSync('git',['show','d977bde1b612bd1ee0335296a918039bf084a84f:src/data/apps.ts'],{encoding:'utf8'});
const source=readFileSync(new URL('../src/data/apps.ts',import.meta.url),'utf8');const base=execFileSync('git',['show','6abaab837eb915372167f37d4fafef6a08f8f404:src/data/apps.ts'],{encoding:'utf8'});const block=s=>s.match(/const words: AppMeta = \{([\s\S]*?)\n\};/)[1];const b=block(source);const locale=l=>b.match(new RegExp('    '+l+': \\{([\\s\\S]*?)\\n    \\},'))[1];
for(const l of ['ko','ja','en'])test(l+': writing is iOS-qualified self-comparison, with no automated grades',()=>{const z=locale(l);assert.ok(z.includes('iOS'));const rules={ko:['뜻을 보고','직접 비교','자동 채점','획순 평가'],ja:['意味を見て','自分で比べ','自動採点','筆順評価'],en:['learned words','compare answers yourself','automatic grading','stroke-order checks']};for(const s of rules[l])assert.ok(z.includes(s),s);assert.ok(z.includes("icon: 'fa-pen'"));});
test('No claims of actual test equivalence, memory guarantee, prediction or advertising-only network',()=>{assert.doesNotMatch(b,/시험 출제 유형 그대로|시험이 묻는 방식 그대로|외운 단어는 오래 남고|잊을 때쯤|출제 유형 맞춤|出題形式そのまま|長く記憶|忘れる頃|actually test|keeps words in memory|right before you forget|only used to show ads|광고 표시에만|広告表示にのみ/);});
test('Network explanation includes stores and restore in all locales',()=>{for(const s of ['광고와 스토어 이용, 구매 복원','広告・ストア・購入の復元','Ads, stores and purchase restoration'])assert.ok(b.includes(s));});
test('SM-2 describes scheduling, not handwriting altering study records',()=>{for(const s of ['학습 응답에 따라','学習の回答に応じて','from your study responses'])assert.ok(b.includes(s));assert.doesNotMatch(b,/handwriting.*SM-2|손글씨.*숙련|手書き.*正答判定/);});
test('Dated writing patch kept pay boundaries, previous names, decks, screenshots and CTA destinations',()=>{const old=block(base);const dated=block(wordsReceipt);const datedLocale=l=>dated.match(new RegExp('    '+l+': \\{([\\s\\S]*?)\\n    \\},'))[1];for(const l of ['ko','ja','en']){const o=old.match(new RegExp('    '+l+': \\{([\\s\\S]*?)\\n    \\},'))[1],n=datedLocale(l);for(const key of ['tagline','shotsTitle','featuresTitle','ctaTitle','ctaSub'])assert.equal(n.match(new RegExp(key+": '([^']*)'"))[1],o.match(new RegExp(key+": '([^']*)'"))[1]);assert.equal(n.match(/shots: \[([\s\S]*?)\n      \]/)[1],o.match(/shots: \[([\s\S]*?)\n      \]/)[1]);}assert.equal(dated.slice(0,dated.indexOf('  content:')),old.slice(0,old.indexOf('  content:')));});
// The historical patch-scope receipt must not freeze unrelated app copy forever.
test('Dated Words patch preserved every non-Words source byte',()=>{assert.equal(wordsReceipt.replace(/const words: AppMeta = \{[\s\S]*?\n\};/,'WORDS'),base.replace(/const words: AppMeta = \{[\s\S]*?\n\};/,'WORDS'));});
test('Current Words matches verified copy except exact EN name and download-boundary clarifications',()=>{const expected=block(wordsReceipt).replace("featuresTitle: 'Why PiPi Words'","featuresTitle: 'Why Vocab Routine'").replace("ctaSub: 'Free to download. Offers in-app purchases.'","ctaSub: 'Free download with ads and study limits. Optional word packs or a subscription.'");assert.equal(block(source),expected);});
test('Dated public receipt does not imply Android handwriting or learning efficacy verified',()=>{const v=JSON.parse(readFileSync(new URL('../docs/release/words-copy-facts-20261008.json',import.meta.url),'utf8'));assert.equal(v.iosVersion,'1.0.12');assert.match(v.scope,/Android.*not verified/);assert.equal(Object.keys(v.sources).length,3);});

test('KO feature wrapping is Words-only, keeps words intact and never shrinks type',()=>{const css=readFileSync(new URL('../public/styles-app-landing.css',import.meta.url),'utf8');assert.match(css,/:lang\(ko\) \.app-page--words \.app-feature h3,[\s\S]*word-break: keep-all;[\s\S]*overflow-wrap: normal;[\s\S]*text-wrap: pretty;/);const tpl=readFileSync(new URL('../src/components/AppLanding.astro',import.meta.url),'utf8');assert.ok(tpl.includes("'app-page--words': app.slug === 'pipi-words'"));});
